### ISSUE TITLE
Possible problem with symmetry breaking

### ISSUE THREAD

**Issue by alcinocunha** [haslab/Electrum2#3]
In this model
```
var sig A {}
var sig B extends A {}
run {} for 2
```
If you fork the initial state a repeated state will appear, but with the trace extended to length 2. Not sure if there is a problem with symmetry breaking.

**Comment by nmacedo** [comment]
This one is very tricky, and not properly a bug on symmetry breaking, but a consequence of it being oblivious of time. Let `Xi_j` denote atom `i` belongs to sig `X` in time `j`. One of the solutions is simply `B1_0`, which is negated during navigation, and eventually `{B0_0,A1_1}` is returned. The first state is not considered symmetric due to the way the symmetry breaking predicate is generated, which in this case:

`[A0_0,A0_1,B0_0,B0_1] <= [A1_0,A1_1,B1_0,B1_1]`

Meaning that symmetry breaking is "led" by `A` atoms in any state, before `B` being considered. One solution would be to order the predicate on time, generating instead:

`[A0_0,B0_0,A0_1,B0_1] <= [A1_0,B1_0,A1_1,B1_1]`

This would now give priority to the removal of symmetric states.

**Comment by alcinocunha** [comment]
I'm a bit confused and I don't see the relation between my issue and your explanation. The issue I had was that one instance with B0_0 was returned and by keeping forking B0_0,A0_1 was returned. The idea of fork in this case was to exclude initial states with B0, so the second trace should not be returned. And this only happens with B0 - all the other possible initial states are not repeated.

**Comment by nmacedo** [comment]
Fixed at Pardinus level.
